/**
 * Every Arabic string the app can show, in reading order, in one file.
 *
 *   npm run preview:rtl        →  .superpowers/rtl-proof.md
 *
 * WHY THIS EXISTS. `tests/components/rtl.test.tsx` proves no Latin digit and no
 * Latin unit reaches Arabic copy. It cannot prove the Arabic is *right* — that
 * `حوالي ١٢ كم إضافية على مسارك` reads as a sentence rather than four English
 * fragments wearing Arabic. Only a reader can, and a reader needs the strings
 * laid out somewhere that is not a running app on a phone they do not have.
 *
 * It is the same argument `preview:map` makes. That script exists because only
 * an eye that knows the country can see a pin in the wrong town; this one exists
 * because only a reader of Arabic can see a sentence in the wrong order.
 *
 * IT SHOWS COPY, NOT LAYOUT. Mirroring is asserted in rtl.test.tsx and settled
 * on a device, never here.
 *
 * It runs through jest rather than plain node because `@/i18n` is compiled by
 * the same Babel/Metro pipeline the app uses, and reaching it from a bare .mjs
 * would mean maintaining a second module resolution. `jest.config.js` matches
 * only `tests/**\/*.test.ts(x)`, so this file never runs as part of the suite.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { dictionaries, initLanguage } from '@/i18n';

/**
 * Grouped by the screen a string appears on, not alphabetically — a reviewer
 * walks the product, and nobody uses the product in alphabetical order.
 */
const GROUPS: { title: string; prefixes: string[] }[] = [
  { title: 'Getting in (N1–N6) — deferred with P2, still shipped copy', prefixes: ['auth.', 'error.', 'role.'] },
  { title: 'Shipper home (S1, S2)', prefixes: ['home.', 'cust.'] },
  { title: 'Booking (S3–S9)', prefixes: ['book.', 'post.', 'step.', 'load.', 'review.'] },
  { title: 'Price and tracking (T1–T5)', prefixes: ['price.', 'track.', 'pos.', 'trip.', 'event.', 'note.'] },
  { title: 'Driver (D1–D7)', prefixes: ['drv.', 'driver.', 'leg.', 'loc.'] },
  { title: 'Loads list (X1)', prefixes: ['loads.', 'status.'] },
  { title: 'Account (X2)', prefixes: ['account.', 'whatsapp.'] },
  // Search, pin and details in booking; the same place lines on review, T3/T4, D5 and D7.
  { title: 'Places — booking, review, and the driver at the gate (0041)', prefixes: ['places.'] },
  { title: 'Map labels — seas and countries, every drawn map', prefixes: ['map.'] },
  {
    title: 'Shared chrome',
    prefixes: ['common.', 'tab.', 'label.', 'action.', 'route.', 'date.', 'app.', 'country.', 'truck.', 'weight.', 'offers.', 'routes.'],
  },
];

/** Which bucket a string came from, so a reviewer knows what to trust. */
function provenance(source: string, key: string): string {
  const i = source.indexOf('UNPROOFED DRAFTS');
  const at = source.indexOf(`'${key}':`, i);
  return i !== -1 && at !== -1 ? '**draft**' : 'harvested';
}

it('writes the Arabic proof-sheet', () => {
  initLanguage('ar');

  const source = require('node:fs').readFileSync(resolve('src/i18n/index.ts'), 'utf8') as string;
  const seen = new Set<string>();
  const lines: string[] = [
    '# Arabic proof-sheet',
    '',
    'Generated by `npm run preview:rtl`. Every string the app can show, in Arabic,',
    'grouped by the screen it appears on.',
    '',
    '**What to look for:** a sentence whose words sit in English order; a fragment',
    'reading as a label where it should read as a sentence; a term the company does',
    'not actually use; a Latin digit. Rows marked **draft** are the priority — they',
    'were not lifted from the website or the handoff and nobody who reads Arabic has',
    'seen them.',
    '',
    '**This shows copy, not layout.** Whether the screen mirrors correctly is a',
    'question for a device, and it is still open.',
    '',
  ];

  for (const group of GROUPS) {
    const keys = Object.keys(dictionaries.en)
      .filter((k) => group.prefixes.some((p) => k.startsWith(p)) && !seen.has(k))
      .sort();
    keys.forEach((k) => seen.add(k));
    if (!keys.length) continue;

    lines.push(`## ${group.title}`, '');
    lines.push('| key | English | العربية | source |', '|---|---|---|---|');
    for (const k of keys) {
      const en = dictionaries.en[k as keyof typeof dictionaries.en];
      const ar = dictionaries.ar[k as keyof typeof dictionaries.en] ?? '—';
      const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
      lines.push(`| \`${k}\` | ${cell(en)} | ${cell(ar)} | ${provenance(source, k)} |`);
    }
    lines.push('');
  }

  const ungrouped = Object.keys(dictionaries.en).filter((k) => !seen.has(k));
  if (ungrouped.length) {
    // A key with no group is a key nobody decided where to review. Loud, not silent.
    lines.push('## Ungrouped — add a prefix to GROUPS in scripts/rtl-proof.tsx', '');
    for (const k of ungrouped) lines.push(`- \`${k}\``);
    lines.push('');
  }

  mkdirSync(resolve('.superpowers'), { recursive: true });
  writeFileSync(resolve('.superpowers/rtl-proof.md'), lines.join('\n'), 'utf8');

  // Fails the run rather than quietly writing an incomplete sheet.
  expect(ungrouped).toEqual([]);
  initLanguage('en');
});
